// Métodos en cadenas
// Cree 10 variables de tipo cadena donde almacene valores string en
// Ingles y aplique cada una de los siguientes métodos de cadena
// 1. length
// 2. includes()
// 3. back ticks o templatre strings
// 4. trimStart()
// 5. trimEnd()
// 6. replace
// 7. slice
// 8. split
// 9. ToUpperCase
// 10. ToLowerCase

let cadena1 = "white";
let cadena2 = "yellow";
let cadena3 = "circule";
let cadena4 = "fat";
let cadena5 = "never";
let cadena6 = "mind";
let cadena7 = "cat";
let cadena8 = "bird";
let cadena9 = "red";
let cadena10 = "chickent";

console.log(cadena1.length);
console.log(cadena2.includes("a"));
console.log(`${cadena3} es diferente a la ${cadena4}`);
console.log(cadena4.trimStart("t"));
console.log(cadena5.trimEnd(3));
console.log(cadena6.replace());
console.log(cadena7.slice([0],[2]));
console.log(cadena8.split());
console.log(cadena9.toUpperCase);
console.log(cadena10.toLowerCase);

